//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.Automation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutomationConfigurationManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutomationConfigurationManagerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPS.Automation.AutomationConfigurationManagerResource", typeof(AutomationConfigurationManagerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppServerName.
        /// </summary>
        internal static string AppServerName_Key {
            get {
                return ResourceManager.GetString("AppServerName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATION_BROWSER.
        /// </summary>
        internal static string AUTOMATION_BROWSER_KEY {
            get {
                return ResourceManager.GetString("AUTOMATION_BROWSER_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATION_TEST_ENVIRONMENT.
        /// </summary>
        internal static string AUTOMATION_TEST_ENVIRONMENT_KEY {
            get {
                return ResourceManager.GetString("AUTOMATION_TEST_ENVIRONMENT_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AutomationConfig_DownloadFile_Path {
            get {
                return ResourceManager.GetString("AutomationConfig_DownloadFile_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AutomationConfig_Testdata_Path {
            get {
                return ResourceManager.GetString("AutomationConfig_Testdata_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string BrowserName_Key {
            get {
                return ResourceManager.GetString("BrowserName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD_PATH.
        /// </summary>
        internal static string DOWNLOAD_PATH_Key {
            get {
                return ResourceManager.GetString("DOWNLOAD_PATH_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string Environment_Key {
            get {
                return ResourceManager.GetString("Environment_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extent-config.
        /// </summary>
        internal static string ExtentReportAppConfigFileName {
            get {
                return ResourceManager.GetString("ExtentReportAppConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData.
        /// </summary>
        internal static string InMemoryTestData_Path {
            get {
                return ResourceManager.GetString("InMemoryTestData_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log_Path {
            get {
                return ResourceManager.GetString("Log_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPS.Automation.
        /// </summary>
        internal static string LogFile_Name {
            get {
                return ResourceManager.GetString("LogFile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product_Key {
            get {
                return ResourceManager.GetString("Product_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductName.
        /// </summary>
        internal static string ProductKey {
            get {
                return ResourceManager.GetString("ProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestExecutionReport.
        /// </summary>
        internal static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports_Path {
            get {
                return ResourceManager.GetString("Reports_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShots.
        /// </summary>
        internal static string ScreenShots_Path {
            get {
                return ResourceManager.GetString("ScreenShots_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData.
        /// </summary>
        internal static string TestData_Path {
            get {
                return ResourceManager.GetString("TestData_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESTDATA_PATH.
        /// </summary>
        internal static string TESTDATA_PATH_Key {
            get {
                return ResourceManager.GetString("TESTDATA_PATH_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        internal static string TextSeparator {
            get {
                return ResourceManager.GetString("TextSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string XMLFolderName {
            get {
                return ResourceManager.GetString("XMLFolderName", resourceCulture);
            }
        }
    }
}
