//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.Tests.UIPages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UsersPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsersPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPS.Tests.UIPages.UsersPageResource", typeof(UsersPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&quot;tabs-header&quot;]//div[normalize-space(text())=&apos;Archive&apos;].
        /// </summary>
        internal static string ClickOnTab_Archive_Xpath {
            get {
                return ResourceManager.GetString("ClickOnTab_Archive_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //nav[@role=&apos;navigation&apos;]//div//a[.=&apos;Home&apos;].
        /// </summary>
        internal static string ClickOptionsInLSB_Home_Xpath {
            get {
                return ResourceManager.GetString("ClickOptionsInLSB_Home_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&quot;ArchiveTasksList&quot;]//div[@class=&quot;input-with-icon-content-icon center ph&quot;].
        /// </summary>
        internal static string FillUserDetails_calander_icon_Xpath {
            get {
                return ResourceManager.GetString("FillUserDetails_calander_icon_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[.=&apos;Designation&apos;]/../../following-sibling::div/div/span/input.
        /// </summary>
        internal static string FillUserDetails_CreateUser_PopUp_Designation_Xpath {
            get {
                return ResourceManager.GetString("FillUserDetails_CreateUser_PopUp_Designation_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b13-b18-DropdownGroup.
        /// </summary>
        internal static string FillUserDetails_CreateUser_PopUp_Dropdown_Xpath {
            get {
                return ResourceManager.GetString("FillUserDetails_CreateUser_PopUp_Dropdown_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[.=&apos;Email Address&apos;]/../../following-sibling::div/div/span/input.
        /// </summary>
        internal static string FillUserDetails_CreateUser_PopUp_EmailAddress_Xpath {
            get {
                return ResourceManager.GetString("FillUserDetails_CreateUser_PopUp_EmailAddress_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[.=&apos;Full Name&apos;]/../../following-sibling::div/div/span/input.
        /// </summary>
        internal static string FillUserDetails_CreateUser_PopUp_FullName_Xpath {
            get {
                return ResourceManager.GetString("FillUserDetails_CreateUser_PopUp_FullName_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[.=&apos;Mobile No.&apos;]/../../following-sibling::div/div/span/input.
        /// </summary>
        internal static string FillUserDetails_CreateUser_PopUp_mobileNo_Xpath {
            get {
                return ResourceManager.GetString("FillUserDetails_CreateUser_PopUp_mobileNo_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-type=&quot;select-multiple&quot;]//div/input.
        /// </summary>
        internal static string FillUserDetails_CreateUser_PopUp_Role_Xpath {
            get {
                return ResourceManager.GetString("FillUserDetails_CreateUser_PopUp_Role_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div/button[.=&apos;SUBMIT&apos;].
        /// </summary>
        internal static string FillUserDetails_CreateUser_PopUp_submitbutton_Xpath {
            get {
                return ResourceManager.GetString("FillUserDetails_CreateUser_PopUp_submitbutton_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (//table[@id=&quot;b24-ArchiveTaskTable&quot;]/tbody/tr/td[2])[1].
        /// </summary>
        internal static string FillUserDetails_First_Reference_Number_Xpath {
            get {
                return ResourceManager.GetString("FillUserDetails_First_Reference_Number_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&quot;is-today is-selected&quot;].
        /// </summary>
        internal static string FillUserDetails_Todays_Date_Xpath {
            get {
                return ResourceManager.GetString("FillUserDetails_Todays_Date_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;popover-bottom &apos;]//div[.=&apos;Log Out&apos;].
        /// </summary>
        internal static string OptionInUserProfile_UserProfile_Logout_Xpath {
            get {
                return ResourceManager.GetString("OptionInUserProfile_UserProfile_Logout_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;b1-b7-Content&apos;].
        /// </summary>
        internal static string OptionInUserProfile_UserProfile_Xpath {
            get {
                return ResourceManager.GetString("OptionInUserProfile_UserProfile_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[.=&apos;APPROVE&apos;].
        /// </summary>
        internal static string UserPage_ApproveTheNewlyCreatedUser_Approve_Button_Xpath {
            get {
                return ResourceManager.GetString("UserPage_ApproveTheNewlyCreatedUser_Approve_Button_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&quot;b22-TeamTaskTable&quot;]/tbody/tr/td[2].
        /// </summary>
        internal static string UserPage_ApproveTheNewlyCreatedUser_Reference_Number_Xpath {
            get {
                return ResourceManager.GetString("UserPage_ApproveTheNewlyCreatedUser_Reference_Number_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;margin-y-m&apos;]//button[.=&apos;ADD USER&apos;].
        /// </summary>
        internal static string UserPage_clickOnButtonInUserAccessManagement_AddUser_Xpath {
            get {
                return ResourceManager.GetString("UserPage_clickOnButtonInUserAccessManagement_AddUser_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div/a[.=&apos;User Access Management&apos;].
        /// </summary>
        internal static string UserPage_clickOnTheOption_Settings_UserAccessManagement_Xpath {
            get {
                return ResourceManager.GetString("UserPage_clickOnTheOption_Settings_UserAccessManagement_Xpath", resourceCulture);
            }
        }
    }
}
